<div class="UIpagos">
	<div class="box">
		<h2><b>Mejores Compradores</b></h2>
		<hr>
		<div class="table-responsive">
			<table id="stats" class="table table-striped table-bordered table-sm table-hover">
				<thead>
					<tr>
						<th>Comprador</th>
						<th>Ultimo pago</th>
						<th>Completos</th>
						<th>Pendientes</th>
						<th>Devueltos</th>
						<th>Total Pagos</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
		<hr>
		<div class="table-responsive">
			<table id="buyer" class="table table-striped table-bordered table-sm table-hover">
				<thead>
					<tr>
						<th>Comprador</th>
						<th>Pago min</th>
						<th>Pago max</th>
						<th>x&#x0304;</th>
						<th>&sigma;</th>
						<th>Total Gastado</th>
						<th>Total Devuelto</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>
		</div>
		<hr>
		<a href="productos" class="btn btn-paypal">Productos</a>
		<a href="pagos" class="btn btn-paypal">Pagos</a>
		<a href="index" class="btn btn-paypal">Inicio</a>
	</div>
</div>

<script type="text/javascript">
	$(function() {

		$.ajax({
			url: 'Estadisticas/obtener',
			method: 'POST',
			dataType: 'json'
		}).done(function(data) {

			$.each(data.data, function(i, stat) {
				let row1 = '';
				row1 += '<tr>';
				row1 += `	<td>${stat.mejor_comprador}</td>`;
				row1 += `	<td>${stat.ultimo_pago}</td>`;
				row1 += `	<td>${stat.completos}</td>`;
				row1 += `	<td>${stat.pendientes}</td>`;
				row1 += `	<td>${stat.devueltos}</td>`;
				row1 += `	<td>${stat.total_pagos}</td>`;
				row1 += '</tr>';
				$('#stats tbody').append(row1);

				let row2 = '';
				row2 += '<tr>';
				row2 += `	<td>${stat.mejor_comprador}</td>`;
				row2 += `	<td>$${stat.pago_min}</td>`;
				row2 += `	<td>$${stat.pago_max}</td>`;
				row2 += `	<td>$${stat.gastos_prom}</td>`;
				row2 += `	<td>$${stat.desvest_gastos}</td>`;
				row2 += `	<td>$${stat.total_gastado}</td>`;
				row2 += `	<td>$${stat.total_devuelto}</td>`;
				row2 += '</tr>';
				$('#buyer tbody').append(row2);
			});

		}).fail(function(jqXHR) {
			$('#stats, #buyer').hide();
			console.log(jqXHR);
			showToast('Error al mostrar estadisticas', 'Hubo un error', 'error');
		});

	});
</script>